### PR TITLE
Continuous integration

### PR DESCRIPTION
**Pull request by JoranAngevaare**
Add a few tests that make sure the notebooks run. Actually, this way, we obtain 90% coverage, which is not so bad actually.

In case you want a nice coverage report, you'd probably have to activate it first: https://coveralls.io/github/jelleaalbers/wimprates

See e.g. for my fork
https://coveralls.io/builds/51728636

### CODE REVIEW

**Comment by JoranAngevaare** [comment]
@JelleAalbers if you agree - this one is ready to merge

**Review by JelleAalbers — APPROVED** [review]
This looks great, thanks Joran! Besides the tests the update to the notebooks is very useful. I see you added the `material` argument to a few functions already in this PR, so as you said there will be some overlap with https://github.com/JelleAalbers/wimprates/pull/7. Let's merge this one first then see how that PR looks.

**Comment by JelleAalbers** [comment]
Looks python 3.7 is failing (https://github.com/JelleAalbers/wimprates/runs/7881484124?check_suite_focus=true) since pandas no longer supports 3.7 (https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html). Do you still need python 3.7 or can we disable that build?

**Comment by JoranAngevaare** [comment]
@JelleAalbers , yeah I also noticed in https://github.com/JelleAalbers/wimprates/pull/7/commits/88e2a0ac107cabc5cb070c2b74b9d51e0163556b - I think dropping support for python 3.7 makes a lot of sense.

I also included it in https://github.com/JelleAalbers/wimprates/pull/7

**Pull request merged**
